# generated by datamodel-codegen:
#   filename:  class_schema.json
#   timestamp: 2024-02-25T00:00:31+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Person(BaseModel):
    name: Optional[str] = None
    age: Optional[int] = None
    occupation: Optional[str] = None
